version: '3.1'

volumes:
  app-gems:
    driver: local

services:
  app:
    image: gueils/belugas:development
    build:
      context: .
      dockerfile: dev.Dockerfile
    entrypoint: /usr/src/app/bin/dev-entrypoint
    volumes:
      # Mount our app code directory (".") into our app containers at the `/usr/src/lib` folder:
      - .:/usr/src/app

      # Mount the 'app-gems' volume on the folder that stores bundled gems:
      - app-gems:/usr/local/bundle

      # Mount some example projects:
      - ${BELUGAS_CODE:-./tmp/code_examples/example_project}:/code

      # Mount the docker socket:
      - /var/run/docker.sock:/var/run/docker.sock

      # Mount the temporary folder:
      - ./tmp/fdet:/tmp/fdet

    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as byebug, etc:
    stdin_open: true

    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true

    # The command:
    command: guard

    environment:
      BELUGAS_DOCKER: "true"
      BELUGAS_CODE: ${BELUGAS_CODE:-./tmp/code_examples/example_project}
