# This file lists all the engines available to be run for analysis.
#
# Each engine must have `channels` (with a `stable` key) and `description`. The
# values in `channels` will be passed to `docker run` and so may be any value
# appropriate for that (repo/name:tag, image id, etc).
#
# When a repo has files that match the `enable_regexps`, that engine will be
# enabled by default in the codeclimate.yml file. That file will also have in it
# the `default_ratings_paths` globs, which are used during analysis to determine
# which files should be rated.
#
linguist:
  channels:
    stable: icalialabs/belugas-linguist:latest
  description: Detects the programming languages used in the analyzed project
  community: true

ruby:
  channels:
    stable: icalialabs/belugas-ruby:latest
  description: Static analysis tool which detects features of ruby projects, including rails, etc.
  community: false
  run_if:
    linguist:
      - Ruby

# dotnet:
#   channels:
#     stable: icalialabs/beluga-dotnet
#   description: Static analysis tool which detects features of dotnet projects, including mono, etc.
#   community: false
