# This file lists all the engines available to be run for analysis.
#
# Each engine must have `channels` (with a `stable` key) and `description`. The
# values in `channels` will be passed to `docker run` and so may be any value
# appropriate for that (repo/name:tag, image id, etc).
#
# When a repo has files that match the `enable_regexps`, that engine will be
# enabled by default in the codeclimate.yml file. That file will also have in it
# the `default_ratings_paths` globs, which are used during analysis to determine
# which files should be rated.
#
linguist:
  channels:
    stable: gueils/belugas-linguist:latest
  description: Detects the programming languages used in the analyzed project
  community: true

ruby:
  channels:
    stable: gueils/belugas-ruby:latest
  description: Static analysis tool which detects features of ruby projects, including rails, etc.
  community: false
  run_if:
    # Establishing an engine dependency: Engines that must run before this engine:
    engines:
      - linguist
    # Establish a feature dependency: features that must been detected before running this engine:
    features:
      - Ruby

python:
  channels:
    stable: gueils/belugas-python:latest
  description: Static analysis tool which detects features of python projects, including django, etc.
  community: false
  run_if:
    engines:
      - linguist
    features:
      - Python

java:
  channels:
    stable: gueils/belugas-java:latest
  description: Static analysis tool which detects features of java projects.
  community: false
  run_if:
    engines:
      - linguist
    features:
      - Java

php:
  channels:
    stable: gueils/belugas-php:latest
  description: Static analysis tool which detects features of php projects.
  community: false
  run_if:
    engines:
      - linguist
    features:
      - PHP
node:
  channels:
    stable: gueils/belugas-node:latest
  description: Static analysis tool which detects features of node projects.
  community: false

javascript:
  channels:
    stable: gueils/belugas-node:latest
  description: Static analysis tool which detects features of node projects.
  community: false
  run_if:
    engines::
      - linguist
    features:
      - Javascript

# dotnet:
#   channels:
#     stable: whalesil/beluga-dotnet
#   description: Static analysis tool which detects features of dotnet projects, including mono, etc.
#   community: false
